# Generated by Django 3.2.5 on 2021-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_google_account',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
