# Generated by Django 3.2.5 on 2021-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default/default_image.png', upload_to='products/', verbose_name='Image'),
        ),
    ]
